//! Main binary entry point for openapi_client implementation.
// This is the amended version that adds Authorization via Inversion of Control.

#![allow(missing_docs)]

use clap::{Arg, Command};
use std::fs::OpenOptions;
use std::io::Write;

mod server;
mod server_auth;

/// A writer that duplicates output to both stderr and a file.
struct TeeWriter {
    stderr: std::io::Stderr,
    file: std::fs::File,
}

impl Write for TeeWriter {
    fn write(&mut self, buf: &[u8]) -> std::io::Result<usize> {
        self.stderr.write_all(buf)?;
        self.file.write_all(buf)?;
        Ok(buf.len())
    }

    fn flush(&mut self) -> std::io::Result<()> {
        self.stderr.flush()?;
        self.file.flush()?;
        Ok(())
    }
}

/// Create custom server, wire it to the autogenerated router,
/// and pass it to the web server.
#[tokio::main]
async fn main() {
    dotenvy::dotenv().ok();

    let log_file = OpenOptions::new()
        .create(true)
        .append(true)
        .open("server.log")
        .expect("Failed to open log file");

    env_logger::Builder::from_default_env()
        .target(env_logger::Target::Pipe(Box::new(TeeWriter {
            stderr: std::io::stderr(),
            file: log_file,
        })))
        .init();

    let matches = Command::new("daily_tracker_backend")
        .arg(
            Arg::new("https")
                .long("https")
                .help("Whether to use HTTPS or not"),
        )
        .get_matches();

    let addr = "127.0.0.1:8080";

    server::create(addr, matches.contains_id("https")).await;
}
