//! Main binary entry point for openapi_client implementation.
// This is the amended version that adds Authorization via Inversion of Control.

#![allow(missing_docs)]

use axum::{Router, routing::post};
use logging::init_logging;

// mod server;
mod server_auth;
mod handler;


/// Create custom server, wire it to the autogenerated router,
/// and pass it to the web server.
#[tokio::main]
async fn main() {
    dotenvy::dotenv().ok();
    init_logging();

    // 3. 汇总所有的 API 结构和路由
    // #[derive(OpenApi)]
    // #[openapi(
    //     paths(
    //         get_users // 把上面写的函数名填进来
    //     ),
    //     components(
    //         schemas(User) // 把用到的数据结构填进来
    //     ),
    //     tags(
    //         (name = "User API", description = "用户相关的 API")
    //     )
    // )]
    // struct ApiDoc;

    // 4. 构建 Axum Router，将 Swagger UI 挂载到 /swagger-ui 路径
    let app = register_routes();
    // // 5. 启动服务
    let listener = tokio::net::TcpListener::bind("0.0.0.0:3000").await.unwrap();
    println!("Swagger UI 运行在 http://localhost:3000/swagger-ui");
    axum::serve(listener, app).await.unwrap();
}

fn register_routes() -> Router {
    let app = Router::new()
        .route("/get-topics", post(handler::get_topics));
        // .merge(SwaggerUi::new("/swagger-ui").url("/api-docs/openapi.json", ApiDoc::openapi()))
    return app;
}
